# doc: https://github.com/wei/pull#basic-setup
# manual trigger: https://pull.git.ci/process/${fork-user}/keepassxc
# pull from: https://github.com/keepassxreboot/keepassxc
version: "1"
rules:
  - base: master
    upstream:  keepassxreboot:master
    mergeMethod: hardreset

  - base: develop
    upstream:  keepassxreboot:develop
    mergeMethod: rebase
